### ISSUE TITLE
after several connection, win 2012 r2 does not connect - Error code 3334

### ISSUE THREAD

**Issue by federicozanardi** [kmscode/mRemote3G#19] opened 2016-01-27 12:05 UTC
we I have several connections established to win 2012 r2 (like 3-4-5), next sessions does not open with error:
----------
WarningMsg
27/01/2016 13:04:12
RDP disconnected!

Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again.
Error code 3334.
----------

if I close some older connection, I can connect to new one

**Comment by kmscode** [comment] 2016-01-27 14:51
Try the following on the system where you run mRemote3G:
1. On the system where you run RDCMan, Run "dcomcnfg.exe" 
2.  Expand Component Services, My Computer, Distributed Transaction Coordinator.
3. Right click on "Local DTC" and select properties.
4. Click the "Security" tab
5.  Check the "Network DTC Access" box.  
6. Under "Transaction Manager Communication", select the "No Authentication Required" radio button.

[Souce](https://social.technet.microsoft.com/Forums/windowsserver/en-US/61f218a5-5ef8-49da-a035-90cdd64fc9a0/problem-with-remote-desktop-connection-manager-error-3334?forum=winserverTS)

**Comment by federicozanardi** [comment] 2016-01-28 11:21
tried, same beahviour

**Comment by njeske** [comment] 2016-02-02 19:37
I believe this is an issue with the Windows client OS, and not mRemote3G.  I had this problem using just about any RDP management software on Windows 7 x64.  When using Windows 8.1 and Windows 10, I no longer have this problem.

**Comment by kmscode** [comment] 2016-02-02 22:38
What are the gateway settings for the problem connection(s)? If they are set to "Detect", can you set them to "Never"?

**Comment by njeske** [comment] 2016-02-02 22:49
With every OS I've used iterations of mRemote on (7, 8, 8.1, 10) the gateway settings for all my connections is set to "Never."  However I have only ever experienced the "3334" error when using Windows 7.  Until today, I've been using the latest non-beta of mRemoteNG on both my Windows 10 laptop, and on a Windows 7 VDI (Horizon View) desktop.  After opening anywhere from 5-7 RDP connections on Windows 7, I run the risk of getting the 3334 error when trying to open any more.  On Windows 10, I've had as many as 20+ RDP sessions active without getting the 3334 error a single time.  I'm not sure what causes the problem, but it seems to be specific to Windows 7, and I'm willing to bet that federicozanardi is running Windows 7.

**Comment by federicozanardi** [comment] 2016-02-03 06:57
I have all con with "never"
my OS is win 10 x64 ent full patched

**Comment by njeske** [comment] 2016-02-03 17:47
Interesting.  I've never once had the 3334 error on any of my Windows 10 machines.  If it happens, I'll definitely post about it.

**Comment by kmscode** [comment] 2016-02-10 13:52
Based on comments from #30 and the ["original" bug report](https://mremoteng.atlassian.net/browse/MR-582) this might be fixed either with an x64 build, or an additional compiler option in the 32 bit build. I still have not been able to reproduce this. I'll look into the [compiler option](https://msdn.microsoft.com/en-us/library/wz223b1z.aspx) further.

**Comment by kmscode** [comment] 2016-02-13 14:00
Trying to get #5 resolved - which will also hopefully resolve #24. At which point, I'll add the compiler option to the next build that I release in hopes of resolving this one.

**Comment by ngj5-beasTxx** [comment] 2016-02-24 20:57
Darn I hoped this was fixed when I found this project but can confirm it still is an issue that exisited when I tried out mRemoteNG 1.72/1.73.

https://www.batchworks.de/fix-rdp-error-3334-in-mremoteng-and-others/

This is what I saw as a possible fix as well looks to be the same as the other thread link.

Seems to occur when I try to open more than five rdp sessions more specifically Server 2012 R2. I can confirm this bug has appeared on Windows 8.1 x64 and Windows 10 x64.

**Comment by njeske** [comment] 2016-02-24 21:41
Try the bitmap caching setting fix proposed for issue #14.  I set all of my connection to "no" for that setting and I got 10+ 2012R2 sessions open at the same time without any crashes or 3334 errors.

**Comment by ngj5-beasTxx** [comment] 2016-02-24 21:47
Thanks!!

This seems to be working now I just tested. Just as you did I replaced CacheBitmaps="True" to CacheBitmaps="False" using Notepad++ to edit "confCons.xml" maybe we can make this the default option for new connections?

**Comment by njeske** [comment] 2016-02-24 22:11
Glad it's working for multiple people.  Maybe that will help pin down a proper fix, even if it's simply defaulting that setting to "no".

**Closed** 2016-02-24 22:50 UTC
