### ISSUE TITLE
Anti Virus just flagged this project

### ISSUE THREAD

**Issue by Silent-Joker** [kmscode/mRemote3G#51] opened 2016-03-24 13:25 UTC
My AV just flagged this project.  I sent them an email to find out why.  Not sure what changed suddenly today.

bitdefender.com enterprise

**Comment by kmscode** [comment] 2016-03-24 13:37
Duplicate of #33 

Not sure why either. Scanned locally with McAfee VirusScan Enterprise 8.8. No threats found.

**Closed by kmscode** 2016-03-24 13:37 UTC
Labels: duplicate, invalid, wontfix
