### ISSUE TITLE
Connections sidebar width not saved during restarts.

### ISSUE THREAD

**Issue by damiankaczkowski** [kmscode/mRemote3G#17] opened 2016-01-26 00:42 UTC
As subject says. The 'Connections' sidebar width is not saved between mRemote3G restarts. Old mRemoteNG 1.73 was free from this bug.

VID:
https://www.dropbox.com/s/352k4h8jtbk37d5/VID_20160126_013608.3gp?dl=0

**Comment by kmscode** [comment] 2016-01-26 16:34
This is a duplicate of #6

**Closed by kmscode** 2016-01-26 16:34 UTC
Labels: duplicate
