### ISSUE TITLE
RDP Error 3334 and 264

### ISSUE THREAD

**Issue by damiankaczkowski** [kmscode/mRemote3G#54] opened 2016-04-01 13:51 UTC
I am getting errors like those:

RDP disconnected! Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again.

Error code 3334
RDP disconnected! This computer can't connect to the remote computer. The two computers couldn't connect in the amount of time allotted. Try connecting again. If the problem continues, contact your network administrator or technical support.
Error code 264.

Seems there is a fix on the net at least for 3334 error:
https://www.batchworks.de/fix-rdp-error-3334-in-mremoteng-and-others/

**Comment by kmscode** [comment] 2016-04-01 13:56
Duplicate of #19

**Closed by kmscode** 2016-04-01 13:56 UTC
Labels: duplicate
