### ISSUE TITLE
mRemote3G Window does not come into foreground when clicked

### ISSUE THREAD

**Issue by cookandy** [kmscode/mRemote3G#24] opened 2016-02-04 16:19 UTC
Hello, 

I am having a problem with mRemote3G where the window doesn't come into focus if it's behind another Window.  It sounds identical to this problem:

https://mremoteng.atlassian.net/browse/MR-335
http://forum.mremoteng.org/viewtopic.php?f=4&t=1934#p3614

However, my issue isn't with the task bar button, it's a problem with the window coming into focus when it is not maximized.  For example:

1.  Open mRemote3G in a Window (not full screen)
2.  Open Chrome (or some other window), make sure it's in front of mRemote3G, but so that you can still see the application.
3.  Click on mRemote3G - everything works fine.  The application comes to the foreground as expected.
4.  Open an SSH session in mRemote3G (doesn't seem to affect RDP connections)
5.  Bring Chrome to the foreground
6.  Try to click in the black area (the SSH window) to try to bring mRemote3G to the foreground
7.  You'll notice mRemote3G does not come to the foreground

I tested with the original mRemoteNG and it has the same issue.  I did not experience this issue on Windows 10, but it is present in Windows 7 SP1.

Any ideas on how to fix?

**Comment by Silent-Joker** [comment] 2016-02-04 16:35
I know that Putty has a weird feature like this when you have open documents that it doesn't come forward all the time.  I think this either was or is an issue from putty.  not sure if it was by design.  I noticed before when just using putty only that sometimes when I'm reading a log file in notepad and I click the putty window it doesn't come forward.  I thought it was by design and never said anything as its nice to be able to read the log and type what I need to correct without putty taking over the screen.

not sure if this helps you out.  I cannot do it in Windows 10 of course.  This was when I was on windows 7.

**Comment by cookandy** [comment] 2016-02-04 17:03
I think the problem is due to the Putty window not being "full screen" within mRemote3G.  I notice when I click on the black part of the window, it doesn't work.  However, if I click on the outer part (i.e. the connection list), it comes to the foreground as expected.  Regarding the "full screen", look at this screenshot:

![1](https://cloud.githubusercontent.com/assets/6495064/12822639/388bfa0e-cb26-11e5-8069-cefa8696dbfc.png)

You'll notice in the upper right you can see the bottom of the "minimize", "maximize", and "close" buttons.  Clicking on the middle button confirms that I can restore this Window down:

![2](https://cloud.githubusercontent.com/assets/6495064/12822663/582f03b0-cb26-11e5-8fa0-879bf3793f85.png)

When I click on "maximize" again, I notice there is still a small gap between Putty and mRemote3G.  I don't notice this on Windows 10.

**Comment by jcefoli** [comment] 2016-02-04 17:06
The windowing issue you just described is the same as #5. Maybe it's related to the focus issue.

I also have Windows 10 and when maximizing the window using the sliver of the button that is visible, I still see a part of it:
![image 002](https://cloud.githubusercontent.com/assets/6618013/12822809/be2ec69e-cb37-11e5-99df-f79539712eb1.png)

**Comment by cookandy** [comment] 2016-02-04 17:08
@jcefoli - thanks, it does look like the same issue.  Do you have an issue with foreground focus in Windows 10?

**Comment by cookandy** [comment] 2016-02-04 17:18
Aslo, can you confirm that when your window is "full screen" that you get the "Maximize" button when hovering over the middle button?  It appears that even though it looks maximized, it's really not:

<img width="92" alt="screen shot 2016-02-04 at 10 17 39 am" src="https://cloud.githubusercontent.com/assets/6495064/12823319/89f2ccfe-cb28-11e5-9588-2f06d7d80277.png">

<img width="154" alt="screen shot 2016-02-04 at 10 16 34 am" src="https://cloud.githubusercontent.com/assets/6495064/12823289/680a6d22-cb28-11e5-9af4-558b1df0019e.png">

**Comment by jcefoli** [comment] 2016-02-04 19:19
@cookandy I cannot reproduce the focus issue.  Do you only have the focus issue with PuttyNG, or does it also happen with RDP? If it's just Putty, let's add details to #5 since it could be related to that.

And yes, you are correct. It looks like PuttyNG is intentionally windowed and resizes to fit into the frame. If it's maximized, it puts the whole program window into the mRemote3G frame like your second screenshot.

**Comment by cookandy** [comment] 2016-02-04 19:38
@jcefoli, yes the problem is only with PuttyNG, and not RDP.

**Comment by cookandy** [comment] 2016-02-04 19:45
also, the same is true if I use a custom Putty path and point it to an external version of Putty.

**Comment by kmscode** [comment] 2016-02-05 01:54
I'm pretty sure that I've experienced this also... But I tend to have this maximized as opposed to windowed. I also tend to have all apps maximized (except for open e-mail messages and the occasional notepad used for scratch work) - so clicking in the mremote/putty window is rare for me, but now that you mention it, I think I've had this problem.

As noted, I do run just about everything maximized, so alt+tab and I are very good friends. Now I most certainly noticed problems bring mremote to the front when using alt+tab. It hasn't annoyed me enough to look into it at all. And #5 just kind of drove me nuts researching, so I moved on to some other things for a bit. I'll focus on #5 as soon as I can. Seems very clear now that these problems are related.

**Comment by kmscode** [comment] 2016-02-13 13:57
Still researching #5. Made some minor progress, but also seem to have some how caused more problems (at least on my system). I'm not 100% sure if this one will be fully resolved once #5 is resolved since puttyng is a separate process that is "simply" assigned to mremote as it's parent window... But we'll see.

**Comment by kmscode** [comment] 2016-07-20 16:24
If you're still having problems, please test with:
https://github.com/mRemoteNG/mRemoteNG/releases/tag/v1.74

And report a new bug as needed:
https://mremoteng.atlassian.net/wiki/display/MR/Report+a+Bug

Thanks!

**Closed by kmscode** 2016-07-20 16:24 UTC
