### ISSUE TITLE
inheritance issue

### ISSUE THREAD

**Issue by federicozanardi** [kmscode/mRemote3G#25] opened 2016-02-05 11:04 UTC
consider this situation:

customer1 (with credentials set to user1)
- server1
- server2
- folder DMZ (with other credentials)
--serverd1
--serverd2
- server3 (please note it is child of customer1...)

server3 should connect with creds from customer1, instead mremote use creds from DMZ folder

**Comment by kmscode** [comment] 2016-02-05 15:18
Duplicate of #9

**Closed by kmscode** 2016-02-05 15:18 UTC
Labels: duplicate

**Comment by federicozanardi** [comment] 2016-02-05 16:05
ops ok :)
